<a href="https://colab.research.google.com/github/danieledamaris/renuncias-fiscais-brasil-2024/blob/main/analise_renuncias_fiscais_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Projeto Final - Python para Data Science

Daniele Araujo

Prof. Mayko Costa - SENAI Guarulhos Dutra - Abril/ 2026

Análise sobre as Renúncias Fiscais do Brasil - Ano 2024

Fonte: Portal da Transparência

Referências Bibliográficas



*   Base de Dados Utilizadas: https://portaldatransparencia.gov.br/download-de-dados/renuncias
*   Explicações Conceituais: https://portaldatransparencia.gov.br/entenda-a-gestao-publica/renuncias-fiscais#:~:text=A%20ren%C3%BAncia%20fiscal%20ocorre%20quando%20o%20governo,setor%20privado%20ou%20por%20entidades%20n%C3%A3o%20governamentais

Segundo o Portal da Transparência, a renúncia fiscal ocorre quando o governo abre mão de receber o total ou parte dos tributos devidos em prol de um estímulo da economia ou de programas sociais, que serão desenvolvidos pelo setor privado ou por entidades não governamentais.

Assim, o ato de renunciar a uma receita pública é uma política de governo, com o objetivo, dentre outros, de incentivar o desenvolvimento de setores econômicos estratégicos ou de regiões do país. Esse é o caso, por exemplo, da Zona Franca de Manaus.

In [ ]:
#Renúncias Fiscais

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/projeto_final/2024_RenunciasFiscais.csv', encoding='latin1', sep=';')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [15]:
df.head(5)

,Ano-calendário,CNPJ,Razão Social,Nome Fantasia,Código CNAE,CNAE,Município,UF,Tipo Renúncia,Benefício Fiscal,Fundamento Legal,Descrição,Tributo,Forma Tributação,Valor Renúncia Fiscal (R$)
0,2024,28231767000655,VP FLEXGEN (BRAZIL) SPE LTDA.,NaN,0,Sem informação,BORBA,AM,PIS/COFINS Vinculados à Importação,PIS,"Outras Isenções, Reduções E Suspensões Não Cap...","Valor em real do incentivo, renúncia, benefíci...",PIS,NaN,"8960,00"
1,2024,28231767000655,VP FLEXGEN (BRAZIL) SPE LTDA.,NaN,0,Sem informação,BORBA,AM,PIS/COFINS Vinculados à Importação,COFINS,Bens Submetidos Aos Regimes Aduaneiros Especia...,"Valor em real do incentivo, renúncia, benefíci...",COFINS,NaN,"60645,00"
2,2024,28231767000655,VP FLEXGEN (BRAZIL) SPE LTDA.,NaN,0,Sem informação,BORBA,AM,Imposto de Importação e IPI Vinculado,Imposto de Importação,Admissao No Entreposto Internacional Da Zona F...,"Valor em real do incentivo, renúncia, benefíci...",Imposto de Importação,NaN,"73739,00"
3,2024,28231767000655,VP FLEXGEN (BRAZIL) SPE LTDA.,NaN,0,Sem informação,BORBA,AM,PIS/COFINS Vinculados à Importação,COFINS,"Outras Isenções, Reduções E Suspensões Não Cap...","Valor em real do incentivo, renúncia, benefíci...",COFINS,NaN,"44108,00"
4,2024,28231767000655,VP FLEXGEN (BRAZIL) SPE LTDA.,NaN,0,Sem informação,BORBA,AM,Imposto de Importação e IPI Vinculado,IPI,Amazonia Ocidental - Dl 35668. Art.2 - Dl 1435...,"Valor em real do incentivo, renúncia, benefíci...",IPI,NaN,"11870,00"

In [18]:
#Valor por Tributo
valor_por_tributo = df.groupby('Tributo')['Valor Renúncia Fiscal (R$)'].sum()
valor_por_tributo = valor_por_tributo.sort_values(ascending=False)
valor_por_tributo

Tributo
PIS                      8960,0012274,0057,005372,00356367,0090748,0025...
Imposto de Importação    73739,0052947,00428,008396,003001,00105439,005...
COFINS                   60645,0044108,00288,0024708,001637592,00417009...
IPI                      11870,0024047,00200,0014019,0010005,00872,0020...
Name: Valor Renúncia Fiscal (R$), dtype: object

In [21]:
#Renúncia por UF
renuncia_por_uf = df.groupby('UF')['Valor Renúncia Fiscal (R$)'].sum()
renuncia_por_uf = renuncia_por_uf.sort_values(ascending=False)
renuncia_por_uf.head(5)

UF
RO    91844,0055968,0016787,0037570,0025085,009353,0...
AM    8960,0060645,0073739,0044108,0011870,0012274,0...
RS    8200,002080,009560,001784,00107,0023,0057083,0...
AL    7891,0036260,00923077,00200877,008591,009448,0...
CE    739068,00160833,00103700,0031495,00522369,0011...
Name: Valor Renúncia Fiscal (R$), dtype: object

In [25]:
#Renúncia de PIS por UF
pis_por_uf = df[df['Tributo'] == 'PIS'].groupby('UF')['Valor Renúncia Fiscal (R$)'].sum()
pis_por_uf = pis_por_uf.sort_values(ascending=False)
pis_por_uf.head(5)

UF
AC    90748,0014155,001159,0017798,0025632,002658,00...
AM    8960,0012274,0057,005372,00356367,0010149,0048...
AP    82409,002859,0054399,0035091,006339,006347,003...
AL    7891,00200877,002056,004978,006487,00396389,00...
PR    763,0026081,005067,007654,007958,001988,004780...
Name: Valor Renúncia Fiscal (R$), dtype: object

In [27]:
#Renúncia de Imposto de Importação por UF
impi_por_uf = df[df['Tributo'] == 'Imposto de Importação'].groupby('UF')['Valor Renúncia Fiscal (R$)'].sum()
impi_por_uf = impi_por_uf.sort_values(ascending=False)
impi_por_uf.head(5)

UF
PI    97549,0033208,008590518,0059785,0025981,009843...
TO    974,0036408,00350008,00198256,00434981,0017497...
AC           94893,0016816,00103608,0035371,00147565,00
RO    91844,0037570,0025085,0030373,00504555,0085075...
RR    84300,005082,002896,003679,0021428,0025011,001...
Name: Valor Renúncia Fiscal (R$), dtype: object

In [28]:
#Renúncia de COFINS por UF
cofins_por_uf = df[df['Tributo'] == 'COFINS'].groupby('UF')['Valor Renúncia Fiscal (R$)'].sum()
cofins_por_uf = cofins_por_uf.sort_values(ascending=False)
cofins_por_uf.head(5)

UF
RS    8200,009560,00107,0057083,0017403,0073944,0070...
CE    739068,00522369,0014962,0012033,00265736,00710...
ES    7129,0012588,0054866,007840,0062148,00299832,0...
RO    676836,0021486,002834790,0067983,002992150,004...
SC    658767,001249799,0011883,0034543,00137723,0090...
Name: Valor Renúncia Fiscal (R$), dtype: object

In [29]:
#Renúncia de IPI por UF
ipi_por_uf = df[df['Tributo'] == 'IPI'].groupby('UF')['Valor Renúncia Fiscal (R$)'].sum()
ipi_por_uf = ipi_por_uf.sort_values(ascending=False)
ipi_por_uf.head(5)

UF
RJ    872,00200087,0044505,0063380,0079714,002093434...
AL    8591,0019058,00852441,0080105,0025970,001640,0...
MT    8359,005986,0011359,00200437,00358633,0017809,...
RR    7471,002850,002243,008176,00922,0012227,004863...
RS    70104,0020984,00223898,00295079,004181837,0043...
Name: Valor Renúncia Fiscal (R$), dtype: object