<a href="https://colab.research.google.com/github/danieledamaris/renuncias-fiscais-brasil-2024/blob/main/analise_renuncias_fiscais_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Projeto Final - Python para Data Science

Daniele Araujo

Prof. Mayko Costa - SENAI Guarulhos Dutra - Abril/ 2026

Análise sobre as Renúncias Fiscais do Brasil - Ano 2024

Fonte: Portal da Transparência

Referências Bibliográficas



*   Base de Dados Utilizadas: https://portaldatransparencia.gov.br/download-de-dados/renuncias
*   Explicações Conceituais: https://portaldatransparencia.gov.br/entenda-a-gestao-publica/renuncias-fiscais#:~:text=A%20ren%C3%BAncia%20fiscal%20ocorre%20quando%20o%20governo,setor%20privado%20ou%20por%20entidades%20n%C3%A3o%20governamentais

Segundo o Portal da Transparência, a renúncia fiscal ocorre quando o governo abre mão de receber o total ou parte dos tributos devidos em prol de um estímulo da economia ou de programas sociais, que serão desenvolvidos pelo setor privado ou por entidades não governamentais.

Assim, o ato de renunciar a uma receita pública é uma política de governo, com o objetivo, dentre outros, de incentivar o desenvolvimento de setores econômicos estratégicos ou de regiões do país. Esse é o caso, por exemplo, da Zona Franca de Manaus.

In [ ]:
#Renúncias Fiscais

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/projeto_final/2024_RenunciasFiscais.csv', encoding='latin1', sep=';')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
df.head(5)

,Ano-calendário,CNPJ,Razão Social,Nome Fantasia,Código CNAE,CNAE,Município,UF,Tipo Renúncia,Benefício Fiscal,Fundamento Legal,Descrição,Tributo,Forma Tributação,Valor Renúncia Fiscal (R$)
0,2024,28231767000655,VP FLEXGEN (BRAZIL) SPE LTDA.,NaN,0,Sem informação,BORBA,AM,PIS/COFINS Vinculados à Importação,PIS,"Outras Isenções, Reduções E Suspensões Não Cap...","Valor em real do incentivo, renúncia, benefíci...",PIS,NaN,"8960,00"
1,2024,28231767000655,VP FLEXGEN (BRAZIL) SPE LTDA.,NaN,0,Sem informação,BORBA,AM,PIS/COFINS Vinculados à Importação,COFINS,Bens Submetidos Aos Regimes Aduaneiros Especia...,"Valor em real do incentivo, renúncia, benefíci...",COFINS,NaN,"60645,00"
2,2024,28231767000655,VP FLEXGEN (BRAZIL) SPE LTDA.,NaN,0,Sem informação,BORBA,AM,Imposto de Importação e IPI Vinculado,Imposto de Importação,Admissao No Entreposto Internacional Da Zona F...,"Valor em real do incentivo, renúncia, benefíci...",Imposto de Importação,NaN,"73739,00"
3,2024,28231767000655,VP FLEXGEN (BRAZIL) SPE LTDA.,NaN,0,Sem informação,BORBA,AM,PIS/COFINS Vinculados à Importação,COFINS,"Outras Isenções, Reduções E Suspensões Não Cap...","Valor em real do incentivo, renúncia, benefíci...",COFINS,NaN,"44108,00"
4,2024,28231767000655,VP FLEXGEN (BRAZIL) SPE LTDA.,NaN,0,Sem informação,BORBA,AM,Imposto de Importação e IPI Vinculado,IPI,Amazonia Ocidental - Dl 35668. Art.2 - Dl 1435...,"Valor em real do incentivo, renúncia, benefíci...",IPI,NaN,"11870,00"

In [5]:
df['Valor Renúncia Fiscal (R$)'] = ( df['Valor Renúncia Fiscal (R$)'].str.replace(',', '.', regex=False).astype(float))

In [6]:
#Valor por Tributo
valor_por_tributo = df.groupby('Tributo')['Valor Renúncia Fiscal (R$)'].sum()
valor_por_tributo = valor_por_tributo.sort_values(ascending=False)
valor_por_tributo

Tributo
COFINS                   3.610981e+10
Imposto de Importação    1.824441e+10
IPI                      8.513914e+09
PIS                      7.777234e+09
Name: Valor Renúncia Fiscal (R$), dtype: float64

In [7]:
#Renúncia por UF
renuncia_por_uf = df.groupby('UF')['Valor Renúncia Fiscal (R$)'].sum()
renuncia_por_uf = renuncia_por_uf.sort_values(ascending=False)
renuncia_por_uf.head(5)

UF
SP    1.995484e+10
RJ    1.638967e+10
AM    1.001003e+10
PR    4.790957e+09
MG    3.838809e+09
Name: Valor Renúncia Fiscal (R$), dtype: float64

In [8]:
#Renúncia de PIS por UF
pis_por_uf = df[df['Tributo'] == 'PIS'].groupby('UF')['Valor Renúncia Fiscal (R$)'].sum()
pis_por_uf = pis_por_uf.sort_values(ascending=False)
pis_por_uf.head(5)

UF
SP    2.216273e+09
RJ    1.755831e+09
AM    8.444679e+08
PR    5.286436e+08
MG    4.671264e+08
Name: Valor Renúncia Fiscal (R$), dtype: float64

In [9]:
#Renúncia de Imposto de Importação por UF
impi_por_uf = df[df['Tributo'] == 'Imposto de Importação'].groupby('UF')['Valor Renúncia Fiscal (R$)'].sum()
impi_por_uf = impi_por_uf.sort_values(ascending=False)
impi_por_uf.head(5)

UF
RJ    5.196058e+09
SP    4.811381e+09
AM    2.850589e+09
PR    1.335746e+09
MG    8.385524e+08
Name: Valor Renúncia Fiscal (R$), dtype: float64

In [10]:
#Renúncia de COFINS por UF
cofins_por_uf = df[df['Tributo'] == 'COFINS'].groupby('UF')['Valor Renúncia Fiscal (R$)'].sum()
cofins_por_uf = cofins_por_uf.sort_values(ascending=False)
cofins_por_uf.head(5)

UF
SP    1.027940e+10
RJ    8.217602e+09
AM    3.897880e+09
PR    2.448733e+09
MG    2.167233e+09
Name: Valor Renúncia Fiscal (R$), dtype: float64

In [11]:
#Renúncia de IPI por UF
ipi_por_uf = df[df['Tributo'] == 'IPI'].groupby('UF')['Valor Renúncia Fiscal (R$)'].sum()
ipi_por_uf = ipi_por_uf.sort_values(ascending=False)
ipi_por_uf.head(5)

UF
SP    2.647794e+09
AM    2.417090e+09
RJ    1.220182e+09
ES    4.797912e+08
PR    4.778342e+08
Name: Valor Renúncia Fiscal (R$), dtype: float64

In [13]:
#Importando Bibliotecas para criar os Gráficos
import plotly.express as px
import plotly.graph_objects as go

In [41]:
#Gráfico da Renúncia Fiscal por UF
df_top10_uf = renuncia_por_uf.head(10).reset_index()
df_top10_uf['Valor (Milhões)'] = df_top10_uf['Valor Renúncia Fiscal (R$)'] / 1000000
fig_uf = px.bar(
    df_top10_uf,
    x= 'UF',
    y='Valor (Milhões)',
    title='Top 10 UFs com Maior Renúncia Fiscal',
    text_auto='.2f',
    color= 'Valor (Milhões)',
    color_continuous_scale='YlGn')
fig_uf.update_traces(textposition='outside')
fig_uf.update_yaxes(range=[0, df_top10_uf['Valor (Milhões)'].max() * 1.15])
fig_uf.show()

In [37]:
#Gráfico da Renúncia de PIS por UF
df_top10_pis = pis_por_uf.head(10).reset_index()
df_top10_pis['Valor (Milhões)'] = df_top10_pis['Valor Renúncia Fiscal (R$)'] / 1000000
fig_pis = px.bar(
    df_top10_pis,
    x='UF',
    y='Valor (Milhões)',
    title='Top 10 UFs com Maior Renúncia de PIS (em Milhões de R$)',
    text_auto='.2f',
    color='Valor (Milhões)',
    color_continuous_scale='YlGn' )
fig_pis.update_traces(textposition='outside')
fig_pis.update_yaxes(range=[0, df_top10_pis['Valor (Milhões)'].max() * 1.15])
fig_pis.show()

In [32]:
#Gráfico da Renúncia de Imposto de Importação por UF
df_top10_impi = impi_por_uf.head(10).reset_index()
df_top10_impi['Valor (Milhões)'] = df_top10_impi['Valor Renúncia Fiscal (R$)'] / 1000000
fig_impi = px.bar(
    df_top10_impi,
    x='UF',
    y='Valor (Milhões)',
    title='Top 10 UFs com Maior Renúncia de Imposto de Importação (em Milhões de R$)',
    text_auto='.2f',
    color='Valor (Milhões)',
    color_continuous_scale='YlGn')
fig_impi.update_traces(textposition='outside')
fig_impi.update_yaxes(range=[0, df_top10_impi['Valor (Milhões)'].max() * 1.15])
fig_impi.show()

In [31]:
#Gráfico da Renúncia de COFINS por UF
df_top10_cofins = cofins_por_uf.head(10).reset_index()
df_top10_cofins['Valor (Milhões)'] = df_top10_cofins['Valor Renúncia Fiscal (R$)'] / 1000000
fig_cofins = px.bar(
    df_top10_cofins,
    x='UF',
    y='Valor (Milhões)',
    title='Top 10 UFs com Maior Renúncia de COFINS (em Milhões de R$)',
    text_auto='.2f',
    color= 'Valor (Milhões)',
    color_continuous_scale='YlGn')
fig_cofins.update_traces(textposition='outside')
fig_cofins.update_yaxes(range=[0, df_top10_cofins['Valor (Milhões)'].max() * 1.15])
fig_cofins.show()

In [30]:
#Gráfico da Renúncia de IPI por UF
df_top10_ipi = ipi_por_uf.head(10).reset_index()
df_top10_ipi['Valor (Milhões)'] = df_top10_ipi['Valor Renúncia Fiscal (R$)'] / 1000000
fig_ipi = px.bar(
    df_top10_ipi,
    x= 'UF',
    y='Valor (Milhões)',
    title='Top 10 UFs com Maior Renúncia de IPI (em Milhões de R$)',
    text_auto='.2f',
     color= 'Valor (Milhões)',
    color_continuous_scale='YlGn')
fig_ipi.update_traces(textposition='outside')
fig_ipi.update_yaxes(range=[0, df_top10_ipi['Valor (Milhões)'].max() * 1.15])
fig_ipi.show()